import type { Metadata } from "next";
import { Inter, Maven_Pro } from "next/font/google";
import "/styles/globals.css";
import Navbar from "../../../components/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CU Black Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
          {children}
      </body>
    </html>
  );
}
